### ISSUE TITLE
Kırık link

### ISSUE THREAD

**Issue by Qh0stM4N** [deeplearningturkiye/turkce-derin-ogrenme-kaynaklari#37]
#### Sorun belirtmek istediğiniz satırın tamamı

Comparison of Deep Convolutional Neural Network Structures The effect of layer counts and kernel sizes  (B. Melis ÖZYILDIRIM, Serkan KARTAL)

#### Açıklama
Kırık link sayfaya ulaşılamıyor.

commit with @deeplearningturkiye ref : a48086d159459ea2190356465c2cb5a333a62c09

**Comment by deeplearningturkiye** [comment]
Kırık link referansı bulunan "Comparison of Deep Convolutional Neural Network Structures The effect of layer counts and kernel sizes (B. Melis ÖZYILDIRIM, Serkan KARTAL)" sayfadan kaldırılmıştır.
