### ISSUE TITLE
Blog linkim neden kaldırıldı?

### ISSUE THREAD

**Issue by mrtkp9993** [deeplearningturkiye/turkce-derin-ogrenme-kaynaklari#63]
Blogumun linkini bloglar altına eklemiştim.
https://github.com/deeplearningturkiye/turkce-yapay-zeka-kaynaklari/commit/b1ddea9610da1591aeeb2aa2939a090cfe8d172c#diff-0730bb7c2e8f9ea2438b52e419dd86c9
Neden kaldırıldı?

**Comment by deeplearningturkiye** [comment]
İlginiz için teşekkürler.

**Comment by ulgens** [comment]
@deeplearningturkiye İlgi tamam da neden kaldırıldı onu dememişsiniz.
